backend:
  name: github
  repo: omobosteven/stephenomobo.com
  branch: develop

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: assets

site_url: https://www.stephenomobo.com
display_url: https://www.stephenomobo.com

collections:
  - name: about
    label: About
    folder: about
    create: true
    description: A short description of my developer journey
    fields:
      - { name: title, label: Title, widget: string }